version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "diogoribeiro7"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "lockfile-only"
    reviewers:
      - "diogoribeiro7"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/generators"
    schedule:
      interval: "weekly"
    reviewers:
      - "diogoribeiro7"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
