"""
Template management for CLI
"""

from pathlib import Path
from jinja2 import Template


def get_template(name: str) -> str:
    """Get template content by name."""
    templates = {
        "schema/microservice": """-- {{ database_name }} Microservice Schema
-- Engine: {{ engine }}
-- Generated by MySQL Schema CLI

CREATE DATABASE IF NOT EXISTS `{{ database_name }}`
  CHARACTER SET {{ charset }}
  COLLATE {{ collation }};

USE `{{ database_name }}`;

-- Core entities table
CREATE TABLE IF NOT EXISTS `entities` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `data` JSON,
  `version` INT DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_uuid` (`uuid`),
  KEY `idx_type` (`type`),
  KEY `idx_created_at` (`created_at`)
) ENGINE={{ engine }};

-- Events for event sourcing
CREATE TABLE IF NOT EXISTS `events` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `aggregate_id` VARCHAR(36) NOT NULL,
  `event_type` VARCHAR(100) NOT NULL,
  `event_data` JSON,
  `event_version` INT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_aggregate_id` (`aggregate_id`),
  KEY `idx_event_type` (`event_type`),
  KEY `idx_created_at` (`created_at`)
) ENGINE={{ engine }};

{% if with_indexes %}
-- Additional indexes for performance
CREATE INDEX `idx_entities_type_created` ON `entities` (`type`, `created_at`);
CREATE INDEX `idx_events_aggregate_type` ON `events` (`aggregate_id`, `event_type`);
{% endif %}

{% if with_triggers %}
-- Audit trigger
DELIMITER $$
CREATE TRIGGER `entities_audit` AFTER UPDATE ON `entities`
FOR EACH ROW
BEGIN
  INSERT INTO `audit_log` (`entity_id`, `action`, `old_data`, `new_data`, `changed_at`)
  VALUES (NEW.id, 'UPDATE', JSON_OBJECT('version', OLD.version), JSON_OBJECT('version', NEW.version), NOW());
END$$
DELIMITER ;
{% endif %}
""",
        "schema/warehouse": """-- {{ database_name }} Data Warehouse Schema
-- Generated by MySQL Schema CLI

CREATE DATABASE IF NOT EXISTS `{{ database_name }}`
  CHARACTER SET {{ charset }}
  COLLATE {{ collation }};

USE `{{ database_name }}`;

-- Dimension: Date
CREATE TABLE IF NOT EXISTS `dim_date` (
  `date_key` INT NOT NULL,
  `date` DATE NOT NULL,
  `year` INT,
  `quarter` INT,
  `month` INT,
  `week` INT,
  `day_of_week` INT,
  `is_weekend` BOOLEAN,
  `is_holiday` BOOLEAN,
  PRIMARY KEY (`date_key`)
) ENGINE={{ engine }};

-- Dimension: Customer
CREATE TABLE IF NOT EXISTS `dim_customer` (
  `customer_key` INT NOT NULL AUTO_INCREMENT,
  `customer_id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(200),
  `email` VARCHAR(200),
  `segment` VARCHAR(50),
  `created_date` DATE,
  PRIMARY KEY (`customer_key`),
  UNIQUE KEY `idx_customer_id` (`customer_id`)
) ENGINE={{ engine }};

-- Fact: Sales
CREATE TABLE IF NOT EXISTS `fact_sales` (
  `sales_key` BIGINT NOT NULL AUTO_INCREMENT,
  `date_key` INT NOT NULL,
  `customer_key` INT NOT NULL,
  `product_key` INT NOT NULL,
  `quantity` INT,
  `unit_price` DECIMAL(10, 2),
  `total_amount` DECIMAL(12, 2),
  `discount_amount` DECIMAL(10, 2),
  PRIMARY KEY (`sales_key`),
  KEY `idx_date` (`date_key`),
  KEY `idx_customer` (`customer_key`),
  FOREIGN KEY (`date_key`) REFERENCES `dim_date` (`date_key`),
  FOREIGN KEY (`customer_key`) REFERENCES `dim_customer` (`customer_key`)
) ENGINE={{ engine }};

{% if with_partitions %}
-- Partitioning for fact table
ALTER TABLE `fact_sales`
PARTITION BY RANGE (YEAR(date_key)) (
  PARTITION p2023 VALUES LESS THAN (2024),
  PARTITION p2024 VALUES LESS THAN (2025),
  PARTITION p2025 VALUES LESS THAN (2026),
  PARTITION p_future VALUES LESS THAN MAXVALUE
);
{% endif %}
""",
    }
    return templates.get(name, "")


def render_template(template_str: str, context: dict) -> str:
    """Render template with context."""
    template = Template(template_str)
    return template.render(**context)