-- ============================================================================
-- Partitioning (Optional)
-- ============================================================================
-- MySQL does not support foreign keys on partitioned InnoDB tables.
-- This file is intentionally left as a no-op for CI compatibility.
