-- ============================================================================
-- IoT Garbage Bin Monitoring System - Load Generated Data
-- ============================================================================
-- Description: Loads data from CSV files generated by the Python generator
-- Dependencies: All schema files (00-05) must be run first
-- Usage: Run this after generating data with generators/iot_bins/generate.py
-- ============================================================================

USE iot_bins;

-- Disable foreign key checks and autocommit for faster loading
SET foreign_key_checks = 0;
SET autocommit = 0;
SET unique_checks = 0;

-- ============================================================================
-- Load Districts
-- ============================================================================
LOAD DATA LOCAL INFILE '../../generators/iot_bins/output/districts.csv'
INTO TABLE districts
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(district_code, name, area_km2, population);

COMMIT;
SELECT CONCAT('Loaded ', ROW_COUNT(), ' districts') AS Status;

-- ============================================================================
-- Load Bins
-- ============================================================================
LOAD DATA LOCAL INFILE '../../generators/iot_bins/output/bins.csv'
INTO TABLE bins
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(bin_code, district_id, bin_type, capacity_liters, latitude, longitude,
 address, location_type, installation_date, last_maintenance_date, status);

COMMIT;
SELECT CONCAT('Loaded ', ROW_COUNT(), ' bins') AS Status;

-- ============================================================================
-- Load Sensors
-- ============================================================================
LOAD DATA LOCAL INFILE '../../generators/iot_bins/output/sensors.csv'
INTO TABLE sensors
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(sensor_code, bin_id, sensor_type, manufacturer, model, firmware_version,
 installation_date, reading_frequency_seconds, battery_level, last_reading_time, status);

COMMIT;
SELECT CONCAT('Loaded ', ROW_COUNT(), ' sensors') AS Status;

-- ============================================================================
-- Load Collection Routes
-- ============================================================================
LOAD DATA LOCAL INFILE '../../generators/iot_bins/output/collection_routes.csv'
INTO TABLE collection_routes
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(route_code, district_id, route_name, route_type, estimated_duration_minutes,
 estimated_distance_km, active);

COMMIT;
SELECT CONCAT('Loaded ', ROW_COUNT(), ' collection routes') AS Status;

-- ============================================================================
-- Load Route Bin Assignments
-- ============================================================================
LOAD DATA LOCAL INFILE '../../generators/iot_bins/output/route_bin_assignments.csv'
INTO TABLE route_bin_assignments
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(route_id, bin_id, collection_order, estimated_collection_time, notes);

COMMIT;
SELECT CONCAT('Loaded ', ROW_COUNT(), ' route bin assignments') AS Status;

-- ============================================================================
-- Load Trucks
-- ============================================================================
LOAD DATA LOCAL INFILE '../../generators/iot_bins/output/trucks.csv'
INTO TABLE trucks
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(truck_code, license_plate, manufacturer, model, year, capacity_kg,
 fuel_type, last_maintenance_date, next_maintenance_date, odometer_km, status);

COMMIT;
SELECT CONCAT('Loaded ', ROW_COUNT(), ' trucks') AS Status;

-- ============================================================================
-- Load Drivers
-- ============================================================================
LOAD DATA LOCAL INFILE '../../generators/iot_bins/output/drivers.csv'
INTO TABLE drivers
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(employee_id, first_name, last_name, email, phone,
 license_number, license_expiry_date, hire_date, status);

COMMIT;
SELECT CONCAT('Loaded ', ROW_COUNT(), ' drivers') AS Status;

-- ============================================================================
-- Load Collection Schedules
-- ============================================================================
LOAD DATA LOCAL INFILE '../../generators/iot_bins/output/collection_schedules.csv'
INTO TABLE collection_schedules
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(route_id, truck_id, driver_id, scheduled_date, scheduled_start_time,
 scheduled_end_time, status, actual_start_time, actual_end_time, notes);

COMMIT;
SELECT CONCAT('Loaded ', ROW_COUNT(), ' collection schedules') AS Status;

-- ============================================================================
-- Load Collection Events
-- ============================================================================
LOAD DATA LOCAL INFILE '../../generators/iot_bins/output/collection_events.csv'
INTO TABLE collection_events
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(bin_id, schedule_id, truck_id, driver_id, collected_at,
 fill_level_before, weight_kg, collection_duration_seconds, notes);

COMMIT;
SELECT CONCAT('Loaded ', ROW_COUNT(), ' collection events') AS Status;

-- ============================================================================
-- Load Sensor Readings (Large Dataset - Load in Chunks)
-- ============================================================================
-- Note: For very large datasets, consider using mysqlimport or splitting the file

LOAD DATA LOCAL INFILE '../../generators/iot_bins/output/sensor_readings.csv'
INTO TABLE sensor_readings
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(sensor_id, reading_time, reading_value, unit, quality);

COMMIT;
SELECT CONCAT('Loaded ', ROW_COUNT(), ' sensor readings') AS Status;

-- ============================================================================
-- Load Sensor Readings Hourly Aggregates
-- ============================================================================
LOAD DATA LOCAL INFILE '../../generators/iot_bins/output/sensor_readings_hourly.csv'
INTO TABLE sensor_readings_hourly
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(sensor_id, hour_start, min_value, max_value, avg_value, reading_count,
 quality_good_count, quality_warning_count, quality_error_count);

COMMIT;
SELECT CONCAT('Loaded ', ROW_COUNT(), ' hourly aggregates') AS Status;

-- ============================================================================
-- Load Sensor Readings Daily Aggregates
-- ============================================================================
LOAD DATA LOCAL INFILE '../../generators/iot_bins/output/sensor_readings_daily.csv'
INTO TABLE sensor_readings_daily
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(sensor_id, date, min_value, max_value, avg_value, peak_hour, peak_value,
 reading_count, quality_good_pct, quality_warning_pct, quality_error_pct);

COMMIT;
SELECT CONCAT('Loaded ', ROW_COUNT(), ' daily aggregates') AS Status;

-- ============================================================================
-- Load Alert Thresholds
-- ============================================================================
LOAD DATA LOCAL INFILE '../../generators/iot_bins/output/alert_thresholds.csv'
INTO TABLE alert_thresholds
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(name, bin_type, sensor_type, warning_value, critical_value,
 check_interval_seconds, active);

COMMIT;
SELECT CONCAT('Loaded ', ROW_COUNT(), ' alert thresholds') AS Status;

-- ============================================================================
-- Load Alerts
-- ============================================================================
LOAD DATA LOCAL INFILE '../../generators/iot_bins/output/alerts.csv'
INTO TABLE alerts
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(bin_id, sensor_id, threshold_id, alert_type, severity, triggered_at,
 resolved_at, alert_value, message, acknowledged, acknowledged_by, acknowledged_at);

COMMIT;
SELECT CONCAT('Loaded ', ROW_COUNT(), ' alerts') AS Status;

-- ============================================================================
-- Load Fill Rate Predictions (If Generated)
-- ============================================================================
-- Uncomment if predictions are generated
-- LOAD DATA LOCAL INFILE '../../generators/iot_bins/output/fill_rate_predictions.csv'
-- INTO TABLE fill_rate_predictions
-- FIELDS TERMINATED BY ','
-- ENCLOSED BY '"'
-- LINES TERMINATED BY '\n'
-- IGNORE 1 ROWS
-- (bin_id, prediction_date, prediction_hour, predicted_fill_rate,
--  confidence_score, model_version);
--
-- COMMIT;
-- SELECT CONCAT('Loaded ', ROW_COUNT(), ' predictions') AS Status;

-- ============================================================================
-- Re-enable constraints
-- ============================================================================
SET foreign_key_checks = 1;
SET unique_checks = 1;
SET autocommit = 1;

-- ============================================================================
-- Verify Data Loading
-- ============================================================================
SELECT 'Data Loading Summary' AS Report;
SELECT '===================' AS '';

SELECT
    'districts' AS table_name,
    COUNT(*) AS row_count
FROM districts
UNION ALL
SELECT 'bins', COUNT(*) FROM bins
UNION ALL
SELECT 'sensors', COUNT(*) FROM sensors
UNION ALL
SELECT 'collection_routes', COUNT(*) FROM collection_routes
UNION ALL
SELECT 'route_bin_assignments', COUNT(*) FROM route_bin_assignments
UNION ALL
SELECT 'trucks', COUNT(*) FROM trucks
UNION ALL
SELECT 'drivers', COUNT(*) FROM drivers
UNION ALL
SELECT 'collection_schedules', COUNT(*) FROM collection_schedules
UNION ALL
SELECT 'collection_events', COUNT(*) FROM collection_events
UNION ALL
SELECT 'sensor_readings', COUNT(*) FROM sensor_readings
UNION ALL
SELECT 'sensor_readings_hourly', COUNT(*) FROM sensor_readings_hourly
UNION ALL
SELECT 'sensor_readings_daily', COUNT(*) FROM sensor_readings_daily
UNION ALL
SELECT 'alert_thresholds', COUNT(*) FROM alert_thresholds
UNION ALL
SELECT 'alerts', COUNT(*) FROM alerts;

-- ============================================================================
-- Analyze Tables for Query Optimization
-- ============================================================================
ANALYZE TABLE districts;
ANALYZE TABLE bins;
ANALYZE TABLE sensors;
ANALYZE TABLE collection_routes;
ANALYZE TABLE route_bin_assignments;
ANALYZE TABLE trucks;
ANALYZE TABLE drivers;
ANALYZE TABLE collection_schedules;
ANALYZE TABLE collection_events;
ANALYZE TABLE sensor_readings;
ANALYZE TABLE sensor_readings_hourly;
ANALYZE TABLE sensor_readings_daily;
ANALYZE TABLE alert_thresholds;
ANALYZE TABLE alerts;

SELECT 'Data loaded and tables analyzed successfully' AS Status;
